project:
  type: website

website:
  title: "testTentative1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - code-java.qmd

format:
  html:
    theme: journal
    toc: true



